/**
 * Generated by FITpro Fixture Generator
 */
package Fixtures.Mat;

import fit.ActionFixture;

/*
 * TODO: modify class to match the FIT test - edit and add methods as required.
 */
public class CreateNewAssignment extends ActionFixture {


    
	public String assignmentFile() {
		// TODO Auto-generated method stub
		return null;
	}
  
    
	public void assignmentFile(String assignmentFile) {
		// TODO Auto-generated method stub
	}
  
    
	public String assignmentNumber() {
		// TODO Auto-generated method stub
		return null;
	}
  
    
	public void assignmentNumber(String assignmentNumber) {
		// TODO Auto-generated method stub
	}
  
    
	public String courseName() {
		// TODO Auto-generated method stub
		return null;
	}
  
    
	public void courseName(String courseName) {
		// TODO Auto-generated method stub
	}
  
    
	public String fileName() {
		// TODO Auto-generated method stub
		return null;
	}
  
    
	public void fileName(String fileName) {
		// TODO Auto-generated method stub
	}
  
    
	public void startAssignment() {
		// TODO Auto-generated method stub
	}
  

}

