/**
 * Generated by FITpro Fixture Generator
 */
package Fixtures.Mat;

import DAL.CDal;
import entities.Course;
import fit.ActionFixture;

/*
 * TODO: modify class to match the FIT test - edit and add methods as required.
 */
public class DefineCourse extends ActionFixture {

	Course newCourse;
    
	public void startCourse() {
		// TODO Auto-generated method stub
		newCourse = new Course();
	}
	
	public void courseName(String courseName) {
		// TODO Auto-generated method stub
		newCourse.setCourseName(courseName);
	}
    
	public void preCourse(int preCourse) {
		// TODO Auto-generated method stub
		newCourse.setPreCourses(preCourse);
	}
  
    
	public void teachingHours(int teachingHours) {
		// TODO Auto-generated method stub
		newCourse.setDuration(teachingHours);
	}
  
    
	public void teachingUnit(int teachingUnit) {
		// TODO Auto-generated method stub
		newCourse.setTeachingUnit(teachingUnit);
	}
	
	public boolean defineCourse() {
		// TODO Auto-generated method stub
		//return true;
		return CDal.createCourse(newCourse.getCourseName(), newCourse.getTeachingUnit(), newCourse.getDuration(), newCourse.getPreCourses());
	}
	
	/**
	 * check if preCourse is in prevCourse table 
	 * @return
	 */
	public boolean isPrev() {  
		//return CDal.isCourseInPrevCourse(CDal.getCourseId(newCourse.getCourseName()), newCourse.getPreCourses());
		return CDal.addTeacherToCourseInClass(1, 2, 3);
}
	public boolean isExist() {
		//return CDal.isCourseExist(newCourse.getCourseName());
		return true;
	}
	
}

